local toys = {
    "clouds_rainbow_rattle",
    "banana_rattle",
    "llama_rattle",
    "golden_maned_unicorn_rattle",
    "camping_2023_log_bench",
    "camping_2023_camping_tent",
    "camping_2023_flashlight",
    "camping_2023_sleeping_bag",
    "camping_2023_guitar",
    "camping_2023_sparkler",
    "camping_2023_bongos",
    "capuchin_2024_handcuffs",
    "capuchin_2024_compass",
    "capuchin_2024_whip_grappling_hook",
    "capuchin_2024_fire_ring_propeller",
    "capuchin_2024_tophat_flying_disc",
    "capuchin_2024_peanut_balloon",
    "capuchin_2024_seal_pogo",
    "capuchin_2024_peanut_friend_chew_toy",
    "desert_2022_cactus_friend_plushie",
    "desert_2022_anhk_pogostick",
    "desert_2022_scarab_grapple",
    "desert_2022_desert_drum",
    "desert_2022_cactus_balloon",
    "desert_2022_crook_throw_toy",
}

local pet_accessories = {
    "pink_heart_glasses",
    "pink_cat_ear_headphones",
}

local vehicles = {
    "amatruck_2023_toy_delivery_truck",
    "beach_2024_airboat",
}

local strollers = {
    "umbrella_stroller",
    "rocket_ship_stroller",
    "basketball_hoop_stroller",
}

local gifts = {
    "small_gift",
    "big_gift",
    "massive_gift",
}

local food = {
    "hot_dog",
    "pizza_slice",
    "cupcake",
}

local pets = {
    "april_fools_2022_mechapup", 
"april_fools_2022_rock", 
"april_fools_2023_sprout_snail", 
"april_fools_2023_pudding_cat", 
"april_fools_2023_tio_de_nadal", 
"april_fools_2023_yule_log_dog", 
"april_fools_2023_fool_egg", 
"aussie_2024_quokka", 
"aussie_2024_tasmanian_devil", 
"aussie_2024_kookaburra", 
"bfriday_2023_mecha_meow", 
"basic_egg_2022_orangutan", 
"basic_egg_2022_mouse", 
"basic_egg_2022_corgi", 
"basic_egg_2022_parakeet", 
"basic_egg_2022_zebra", 
"basic_egg_2022_camel", 
"basic_egg_2022_poodle", 
"basic_egg_2022_ant", 
"basic_egg_2022_donkey", 
"basic_egg_2022_swordfish", 
"retired_egg", 
"basic_egg_2022_ancient_dragon", 
"basic_egg_2022_alicorn", 
"basic_egg_2022_robot", 
"basic_egg_2022_dragonfly", 
"beach_2024_mahi_mahi", 
"beach_2024_nautilus", 
"beach_2024_gold_mahi_mahi", 
"beach_2024_diamond_mahi_mahi", 
"birthday_2022_uplift_butterfly", 
"birthday_2023_birthday_butterfly", 
"birthday_2024_butterfly", 
"sanctuary_2022_purple_bucks_butterfly", 
"sanctuary_2022_green_premium_butterfly", 
"sanctuary_2022_diamond_premium_butterfly", 
"sanctuary_2022_yellow_bucks_butterfly", 
"sanctuary_2022_orange_premium_butterfly", 
"sanctuary_2022_red_bucks_butterfly", 
"camping_2023_firefly", 
"camping_2023_possum", 
"capuchin_2024_princess_capuchin_monkey", 
"capuchin_2024_inmate_capuchin_monkey", 
"capuchin_2024_pirate_ghost_capuchin_monkey", 
"capuchin_2024_preppy_capuchin_monkey", 
"capuchin_2024_capuchin_monkey", 
"capuchin_2024_royal_capuchin_monkey", 
"celestial_2024_glormy_leo", 
"celestial_2024_singularity_beetle", 
"celestial_2024_glormy_hound", 
"celestial_2024_singularity_pisces", 
"celestial_2024_starhopper", 
"celestial_2024_moonlight_moth", 
"chiprac_2023_chipmunk", 
"chiprac_2023_raccoon", 
"danger_2023_owlbear", 
"danger_2023_hippo", 
"danger_2023_blue_ringed_octopus", 
"danger_2023_mosquito", 
"danger_2023_egg", 
"danger_2023_spinosaurus", 
"danger_2023_liger", 
"danger_2023_poison_dart_frog", 
"danger_2023_puffer_fish", 
"danger_2023_piranha", 
"danger_2023_borhyaena_gigantica", 
"danger_2023_angler_fish", 
"danger_2023_lammergeier", 
"ddlm_2024_sugar_axolotl", 
"ddlm_2024_golden_jaguar", 
"ddlm_2024_grave_owl", 
"desert_2022_blue_scarab", 
"desert_2022_abyssinian_cat", 
"desert_2022_black_scarab", 
"desert_2022_gold_scarab", 
"desert_2024_coyote", 
"desert_2024_gila_monster", 
"desert_2024_vulture", 
"desert_2024_criosphinx", 
"desert_2024_armadillo", 
"desert_2024_sandfish", 
"desert_2024_thorny_devil", 
"desert_2024_egg", 
"desert_2024_cactus_friend", 
"desert_2024_rattlesnake", 
"desert_2024_oryx", 
"desert_2024_deathstalker_scorpion", 
"desert_2024_royal_egg", 
"desert_2024_roadrunner", 
"dolls_2023_wrapped_doll", 
"dolls_2023_river", 
"dolls_2023_pinocchio", 
"dolls_2023_dylan", 
"easter_2022_springer_spaniel_black", 
"easter_2022_springer_spaniel_brown", 
"easter_2022_sugar_glider", 
"easter_2024_candy_cane_snail", 
"easter_2024_dotted_eggy", 
"easter_2024_striped_eggy", 
"easter_2024_floral_eggy", 
"easter_2024_candyfloss_chick", 
"fall_2022_pheasant_green", 
"fall_2022_badger", 
"fall_2022_pheasant_brown", 
"fall_2022_pheasant_black", 
"farm_2023_caterpillar", 
"farm_2023_alpaca", 
"farm_2023_rooster", 
"farm_2023_sheepdog", 
"farm_2023_longhorn_cow", 
"farm_2023_canada_goose", 
"fire_dimension_2024_ornate_horned_frog", 
"fire_dimension_2024_wildfire_hawk", 
"fire_dimension_2024_burning_bunny", 
"fire_dimension_2024_volcanic_rhino", 
"fire_dimension_2024_flaming_fox", 
"fossil_2024_brachiosaurus", 
"fossil_2024_ankylosaurus", 
"fossil_2024_velociraptor", 
"fossil_2024_elasmosaurus", 
"fossil_2024_dimorphodon", 
"gosh_2022_therapy_dog", 
"garden_2024_praying_mantis", 
"garden_2024_weevil", 
"garden_2024_rosy_maple_moth", 
"garden_2024_garden_snake", 
"garden_2024_mole", 
"garden_2024_golden_tortoise_beetle", 
"garden_2024_blue_jay", 
"garden_2024_skunk", 
"garden_2024_mushroom_friend", 
"garden_2024_egg", 
"gifthat_november_2024_hippogriff", 
"gorilla_fair_2023_chef_gorilla", 
"gorilla_fair_2023_emperor_gorilla", 
"gorilla_fair_2023_karate_gorilla", 
"gorilla_fair_2023_astronaut_gorilla", 
"gorilla_fair_2023_gorilla", 
"gorilla_fair_2023_albino_gorilla", 
"halloween_2021_scorpion", 
"halloween_2021_black_mummy_cat", 
"halloween_2021_golden_mummy_cat", 
"halloween_2021_skele_dog", 
"halloween_2021_white_mummy_cat", 
"halloween_2021_ghost_dragon", 
"halloween_2021_evil_dachshund", 
"halloween_2022_evil_basilisk", 
"halloween_2022_mule", 
"halloween_2022_chickatrice", 
"halloween_2022_lava_wolf", 
"halloween_2022_evil_chickatrice", 
"halloween_2022_ghost_wolf", 
"halloween_2022_slug", 
"halloween_2022_zombie_wolf", 
"halloween_2022_lava_dragon", 
"halloween_2022_jousting_horse", 
"halloween_2022_undead_jousting_horse", 
"halloween_2022_basilisk", 
"halloween_2022_chimera", 
"halloween_2023_evil_rock", 
"halloween_2023_vampire_dragon", 
"halloween_2023_dire_stag", 
"halloween_2023_scarecrow_cat", 
"halloween_2023_werewolf", 
"halloween_2023_slime", 
"halloween_2023_undead_elk", 
"halloween_2023_cuteacabra", 
"halloween_2023_scarecrow_crow", 
"halloween_2023_ghost", 
"halloween_2023_scarecrow_horse", 
"halloween_2023_ghost_dog", 
"halloween_2023_nightmare_owl", 
"halloween_2023_scarecrow", 
"halloween_2024_grim_dragon", 
"halloween_2024_sea_skeleton_panda", 
"halloween_2024_jekyll_hydra", 
"halloween_2024_ghost_chick", 
"halloween_2024_headless_horse", 
"halloween_2024_marabou_stork", 
"halloween_2024_evil_chick", 
"halloween_2024_zombie_chick", 
"halloween_2024_dracula_parrot", 
"halloween_2024_franken_feline", 
"halloween_2024_pumpkin_friend", 
"halloween_2024_scarebear", 
"halloween_2024_indian_flying_fox", 
"hamstertime_2024_hamster", 
"hamstertime_2024_diamond_hamster", 
"hamstertime_2024_golden_hamster", 
"ice_cream_refresh_2022_golden_king_penguin", 
"ice_cream_refresh_2022_king_penguin", 
"ice_cream_refresh_2022_diamond_king_penguin", 
"ugc_rewards_2023_glacier_moth", 
"jan_refresh_2023_bloodhound", 
"japan_2022_baku", 
"japan_2022_egg", 
"japan_2022_red_crowned_crane", 
"japan_2022_leopard_cat", 
"japan_2022_spider_crab", 
"japan_2022_trapdoor_snail", 
"japan_2022_tanuki", 
"japan_2022_sado_mole", 
"japan_2022_rhino_beetle", 
"japan_2022_maneki_neko", 
"japan_2022_koi_carp", 
"japan_2022_ibis", 
"japan_2022_dugong", 
"jungle_2023_angelfish", 
"jungle_2023_anteater", 
"jungle_2023_ring_tailed_lemur", 
"jungle_2023_fossa", 
"jungle_2023_bird_of_paradise", 
"jungle_2023_cassowary", 
"kiwi_2023_kiwi", 
"lny_2022_tiger_white", 
"lny_2022_tiger", 
"lny_2022_dragon", 
"lny_2022_tiger_gold", 
"lny_2023_qiongchi", 
"lny_2023_moon_bear", 
"lny_2023_moon_rabbit", 
"lny_2023_water_moon_bear", 
"lny_2023_amami_rabbit", 
"lny_2023_water_rabbit", 
"lny_2023_moon_moon_bear", 
"lunar_2024_fanghorn_tortoise", 
"lunar_2024_rice_cake_rabbit", 
"lunar_2024_midnight_dragon", 
"lunar_2024_rainbow_dragon", 
"lures_2023_toasty_red_panda", 
"lures_2023_flaming_zebra", 
"lures_2023_magma_moose", 
"lures_2023_magma_snail", 
"lures_2023_blazing_lion", 
"lures_2023_ash_zebra", 
"meme_2023_feesh", 
"meme_2023_frogspawn", 
"meme_2023_sheeeeep", 
"modular_castles_2023_frost_unicorn", 
"ocean_2024_kraken", 
"ocean_2024_lionfish", 
"ocean_2024_dracula_fish", 
"ocean_2024_sea_angel", 
"ocean_2024_urchin", 
"pib_2022_persian_cat", 
"pool_2023_goldfish", 
"pool_2023_red_sand_dollar", 
"pool_2023_white_sand_dollar", 
"pride_2022_goat", 
"pride_2023_caelum_cervi", 
"rgb_squid", 
"rgb_chameleon", 
"rain_2023_diamond_amazon", 
"rain_2023_ocelot", 
"rain_2023_green_amazon", 
"rain_2023_white_amazon", 
"random_pets_2022_ibex", 
"random_pets_2022_winged_horse", 
"random_pets_sept_2023_pelican", 
"random_pets_sept_2023_eel", 
"gru_2022_zodiac_egg", 
"gru_2022_zodiac_chick", 
"roblox_classic_2024_teapot", 
"royal_palace_2022_corgi", 
"royal_palace_2022_spaniel", 
"seasia_2023_yellow_lipped_sea_krait", 
"seasia_2023_maleo_bird", 
"seasia_2023_naga_dragon", 
"seasia_2023_bali_starling", 
"seasia_2023_tarsier", 
"seasia_2023_tree_kangaroo", 
"seasia_2023_komodo_dragon", 
"seasia_2023_binturong", 
"seasia_2023_malaysian_tapir", 
"seasia_2023_black_macaque", 
"seasia_2023_gecko", 
"seasia_2023_egg", 
"seasia_2023_banded_palm_civet", 
"scottish_2023_highland_cow", 
"scottish_2023_nessie", 
"sky_ux_2023_cuddly_candle", 
"sky_ux_2023_grinmoire", 
"snow_2022_diamond_albatross", 
"snow_2022_ribbon_seal", 
"snow_2022_albatross", 
"snow_2022_golden_albatross", 
"sofahog_2024_groundhog", 
"space_house_2022_space_whale", 
"space_house_2022_capricorn", 
"springfest_2023_border_collie", 
"springfest_2023_flower_power_duckling", 
"springfest_2023_sunrise_duckling", 
"springfest_2023_field_mouse", 
"springfest_2023_happy_duckling", 
"springfest_2023_hare", 
"springfest_2023_wood_pigeon", 
"springfest_2023_goose", 
"star_rewards_2022_pomeranian", 
"star_rewards_2022_orca", 
"subscription_2024_gold_hummingbird", 
"subscription_2024_diamond_hummingbird", 
"subscription_2024_hummingbird", 
"summerfest_2023_hermit_crab", 
"summerfest_2023_ice_cream_crab", 
"summerfest_2023_happy_clam", 
"summerfest_2023_leviathan", 
"summerfest_2023_shark_doggo", 
"summerfest_2023_tortuga_de_la_isla", 
"summerfest_2023_mackerel_shoal", 
"summerfest_2023_pirate_hermit_crab", 
"summerfest_2023_hotdog_dog", 
"summerfest_2023_castle_hermit_crab", 
"summerfest_2023_flying_fish", 
"summerfest_2023_leopard_shark", 
"summerfest_2023_arctic_tern", 
"summerfest_2023_lobster", 
"summerfest_2024_pretty_pony", 
"summerfest_2024_balloon_unicorn", 
"summerfest_2024_majestic_pony", 
"summerfest_2024_bald_eagle", 
"summerfest_2024_kid_goat", 
"summerfest_2024_corn_doggo", 
"summerfest_2024_punk_pony", 
"summerfest_2024_orange_betta_fish", 
"summerfest_2024_blue_betta_fish", 
"summerfest_2024_pink_betta_fish", 
"summerfest_2024_minipig", 
"summerfest_2024_cow_calf", 
"summerfest_2024_show_pony", 
"summerfest_2024_bull", 
"sunshine_2024_black_marlin", 
"sunshine_2024_cheetah", 
"sunshine_2024_peregrine_falcon", 
"sunshine_2024_bush_elephant", 
"ugc_refresh_2023_african_wild_dog", 
"ugc_refresh_2023_lion_cub", 
"ugc_refresh_2023_warthog", 
"ugc_refresh_2023_ostrich", 
"ugc_refresh_2024_jellyfish", 
"ugc_refresh_2024_honey_badger", 
"ugc_rewards_2022_irish_water_spaniel", 
"urban_2023_gargoyle", 
"urban_2023_egg", 
"urban_2023_cockroach", 
"urban_2023_toy_poodle", 
"urban_2023_fly", 
"urban_2023_alley_cat", 
"urban_2023_black_kite", 
"urban_2023_billy_goat", 
"urban_2023_mongoose", 
"urban_2023_tawny_frogmouth", 
"urban_2023_seagull", 
"urban_2023_pigeon", 
"urban_2023_indian_leopard", 
"vip_2022_chow_chow_light_brown", 
"vip_2022_chow_chow_gold", 
"vip_2022_chow_chow_dark_brown", 
"vip_2022_chow_chow_black", 
"diamond_ladybug", 
"monkey", 
"guardian_lion", 
"platypus", 
"ginger_cat", 
"trex", 
"stingray", 
"narwhal", 
"golden_egg", 
"ground_sloth", 
"jungle_egg", 
"black_panther", 
"lavender_dragon", 
"mythic_egg", 
"business_monkey", 
"albino_bat", 
"bandicoot", 
"dingo", 
"diamond_griffin", 
"bunny", 
"shark", 
"farm_egg", 
"meerkat", 
"crocodile", 
"horse", 
"buffalo", 
"fennec", 
"crow", 
"lunar_ox", 
"dragon", 
"shiba", 
"diamond_egg", 
"cracked_egg", 
"bee", 
"giraffe", 
"elf_shrew", 
"skele_rex", 
"cerberus", 
"golden_ladybug", 
"polar_bear", 
"emu", 
"king_bee", 
"dodo", 
"octopus", 
"griffin", 
"sabertooth", 
"ghost_bunny", 
"kitsune", 
"crab", 
"pig", 
"clownfish", 
"llama", 
"dolphin", 
"rhino", 
"lynx", 
"otter", 
"pumpkin", 
"golden_penguin", 
"stegosaurus", 
"dilophosaurus", 
"chocolate_labrador", 
"turkey", 
"golden_dragon", 
"christmas_egg", 
"tasmanian_tiger", 
"golden_unicorn", 
"chick", 
"toy_monkey", 
"phoenix", 
"rabbit", 
"glyptodon", 
"yeti", 
"wyvern", 
"lamb", 
"starter_egg", 
"woolly_mammoth", 
"wolpertinger", 
"goldhorn", 
"wolf", 
"wild_boar", 
"bat_dragon", 
"frog", 
"shadow_dragon", 
"frost_dragon", 
"axolotl", 
"turtle", 
"cow", 
"triceratops", 
"toucan", 
"hydra", 
"swan", 
"snow_owl", 
"starfish", 
"albino_monkey", 
"snowman", 
"ninja_monkey", 
"dog", 
"snow_cat", 
"sloth", 
"deinonychus", 
"koala", 
"silly_duck", 
"hyena", 
"2021_uplift_butterfly", 
"unicorn", 
"red_squirrel", 
"scoob", 
"queen_bee", 
"ocean_egg", 
"merhorse", 
"fossil_egg", 
"monkey_king", 
"santa_dog", 
"cat", 
"bat", 
"safari_egg", 
"royal_egg", 
"2d_kitty", 
"musk_ox", 
"chicken", 
"kirin", 
"drake", 
"kelpie", 
"robin", 
"arctic_reindeer", 
"reindeer", 
"regular_pet_egg", 
"seahorse", 
"arctic_fox", 
"red_panda", 
"rat", 
"zombie_buffalo", 
"brown_bear", 
"sasquatch", 
"practice_dog", 
"ox", 
"flamingo", 
"pterodactyl", 
"pink_egg", 
"pink_cat", 
"owl", 
"panda", 
"elf_hedgehog", 
"evil_unicorn", 
"beaver", 
"penguin", 
"capybara", 
"peacock", 
"diamond_unicorn", 
"parrot", 
"lion", 
"puma", 
"snow_puma", 
"golden_rat", 
"elephant", 
"kangaroo", 
"ladybug", 
"robo_dog", 
"metal_ox", 
"golden_griffin", 
"frost_fury", 
"pet_egg", 
"easter_2020_egg", 
"diamond_dragon", 
"cobra", 
"blue_dog", 
"aussie_egg", 
"winter_2021_snow_leopard", 
"winter_2021_summer_walrus", 
"winter_2021_walrus", 
"winter_2021_st_bernard", 
"winter_2021_golden_walrus", 
"winter_2021_puffin", 
"winter_2021_husky", 
"winter_2021_ice_golem", 
"winter_2022_shetland_pony_dark_brown", 
"winter_2022_wooly_rhino", 
"winter_2022_snowball_pet", 
"winter_2022_ice_moth_dragon", 
"winter_2022_gingerbread_reindeer", 
"winter_2022_strawberry_shortcake_bat_dragon", 
"winter_2022_shetland_pony_white", 
"winter_2022_ice_wolf", 
"winter_2022_shetland_pony_light_brown", 
"winter_2022_steppe_lion", 
"winter_2022_irish_elk", 
"winter_2022_ram", 
"winter_2022_ermine", 
"winter_2023_story_game_egg", 
"winter_2023_beluga_whale", 
"winter_2023_candy_hare", 
"winter_2023_eggnog_dog", 
"winter_2023_chocolate_chip_bat_dragon", 
"winter_2023_snow_monkey", 
"winter_2023_eggnog_hare", 
"winter_2023_christmas_pudding_pup", 
"winter_2023_gingerbread_hare", 
"winter_2023_fleur_de_ice", 
"winter_2023_nutcracker_squirrel", 
"winter_2023_harp_seal", 
"winter_2023_arctic_hare", 
"winter_2023_glacier_kitsune", 
"winter_2023_gingerbread_mouse", 
"winter_2023_peppermint_penguin", 
"woodland_2022_fallow_deer", 
"woodland_2022_woodland_egg", 
"woodland_2022_pine_marten", 
"woodland_2022_red_cardinal", 
"woodland_2022_bullfrog", 
"woodland_2022_woodpecker", 
"woodland_2022_hawk", 
"woodland_2022_red_fox", 
"woodland_2022_salamander", 
}

warn("[DEBUG] LOADING XENIJOS UNHASHER V-1")

-- Dehashing logic
local hashTable = {}

for i, v in pairs(getgc()) do
    if type(v) == "function" and debug.getinfo(v).name == "get_remote_from_cache" then
        wait(0.5)
        local info = debug.getinfo(v)
        local upvalues = debug.getupvalues(v)
        
        if next(upvalues) ~= nil and type(upvalues[1]) == "table" then
            local remoteTable = upvalues[1]
            
            for key, value in pairs(remoteTable) do
                hashTable[value] = key -- Reverse mapping for easier lookup
            end
        end
    end
end

local apiFolder = game:GetService("ReplicatedStorage"):WaitForChild("API")
local ShopAPIBuyItem

for _, remoteTable in pairs(apiFolder:GetDescendants()) do
    if remoteTable:IsA("RemoteEvent") or remoteTable:IsA("RemoteFunction") then
        local originalName = hashTable[remoteTable]
        if originalName then
            remoteTable.Name = originalName

            -- Check if the remote is "ShopAPI/BuyItem"
            if originalName == "ShopAPI/BuyItem" then
                ShopAPIBuyItem = remoteTable
                warn("[DEBUG] Found ShopAPI/BuyItem remote: " .. tostring(remoteTable))
            end
        end
    end
end

if not ShopAPIBuyItem then
    error("[DEBUG] ShopAPI/BuyItem remote not found. Exiting script.")
end

-- Purchase items from any category
local function purchaseItems(itemType, itemList)
    for _, item in ipairs(itemList) do
        local args = {
            [1] = itemType,
            [2] = item,
            [3] = {}
        }
        
        ShopAPIBuyItem:InvokeServer(unpack(args))
        wait(1)
    end
end

-- Function to purchase vehicles
local function buyVehicle(vehicleName)
    local args = {
        [1] = "transport",
        [2] = vehicleName,
        [3] = {}
    }
    
    ShopAPIBuyItem:InvokeServer(unpack(args))
    wait(1)
end

-- Purchase toys
purchaseItems("toys", toys)

-- Purchase pet accessories
purchaseItems("pet_accessories", pet_accessories)

-- Purchase strollers
purchaseItems("strollers", strollers)

-- Purchase gifts
purchaseItems("gifts", gifts)

-- Purchase food
purchaseItems("food", food)

-- Purchase pets
purchaseItems("pets", pets)

-- Purchase vehicles
for _, vehicle in ipairs(vehicles) do
    buyVehicle(vehicle)
end

warn("All purchases completed.")
